//go:build ignore

// generate-models fetches the list of available models from the Anthropic API
// and writes agent/models.generated.go with a context window table.
//
// The Anthropic API does not return context window sizes, so known values are
// seeded below; anything not in the seed table defaults to 1M tokens.
//
// Usage:
//
//	ANTHROPIC_API_KEY=sk-ant-... go run scripts/generate-models.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"
)

// knownWindows maps substrings of model IDs to their context window.
// Order matters — more specific patterns should come first.
var knownWindows = []struct {
	pattern string
	tokens  int64
}{
	// Claude 4.x — 1M context
	{"claude-opus-4", 1_000_000},
	{"claude-sonnet-4", 1_000_000},
	{"claude-haiku-4", 1_000_000},
	// Claude 3.5 — 200K
	{"claude-3-5", 200_000},
	// Claude 3 — 200K
	{"claude-3", 200_000},
}

const defaultTokens = 1_000_000

func contextWindowFor(modelID string) int64 {
	lower := strings.ToLower(modelID)
	for _, kw := range knownWindows {
		if strings.Contains(lower, kw.pattern) {
			return kw.tokens
		}
	}
	return defaultTokens
}

type modelEntry struct {
	ID            string
	ContextWindow int64
}

func fetchModels(apiKey string) ([]modelEntry, error) {
	req, err := http.NewRequest("GET", "https://api.anthropic.com/v1/models", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("API returned %d: %s", resp.StatusCode, body)
	}

	var result struct {
		Data []struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("parse response: %w", err)
	}

	entries := make([]modelEntry, 0, len(result.Data))
	for _, m := range result.Data {
		entries = append(entries, modelEntry{
			ID:            m.ID,
			ContextWindow: contextWindowFor(m.ID),
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })
	return entries, nil
}

const fileTemplate = `// Code generated by scripts/generate-models.go — do not edit manually.
// Run: ANTHROPIC_API_KEY=sk-ant-... go run scripts/generate-models.go
// Generated: {{ .Timestamp }}
//
// Context windows are not returned by the Anthropic API; values come from
// known model metadata. Unknown models default to {{ .Default }} tokens.

package agent

// modelContextWindows maps exact model IDs to their input context window.
// contextWindowForModel does a substring match against this table.
var modelContextWindows = map[string]int64{
{{- range .Models }}
	{{ printf "%q" .ID }}: {{ .ContextWindow }},
{{- end }}
}
`

func main() {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintln(os.Stderr, "ANTHROPIC_API_KEY is required")
		os.Exit(1)
	}

	fmt.Fprintln(os.Stderr, "Fetching models from Anthropic API...")
	models, err := fetchModels(apiKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Got %d models\n", len(models))

	tmpl := template.Must(template.New("models").Parse(fileTemplate))
	data := struct {
		Timestamp string
		Default   int64
		Models    []modelEntry
	}{
		Timestamp: time.Now().UTC().Format("2006-01-02"),
		Default:   defaultTokens,
		Models:    models,
	}

	out, err := os.Create("agent/models.generated.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Create file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	if err := tmpl.Execute(out, data); err != nil {
		fmt.Fprintf(os.Stderr, "Template: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "Written: agent/models.generated.go")
}
